## Notebook 10 – Combining Datasets

### 1. concat()

In [ ]:
concat() is used to combine two or more DataFrames either:

Vertically (row-wise)
Horizontally (column-wise)

Syntax

pd.concat([df1, df2])

#### Vertical Concatenation (Default)

In [1]:
import pandas as pd

df1 = pd.DataFrame({
    'Name': ['Hari', 'Anu']
})

df2 = pd.DataFrame({
    'Name': ['Ravi', 'Kiran']
})

pd.concat([df1, df2])

    Name
0   Hari
1    Anu
0   Ravi
1  Kiran

**Notice duplicate indexes.**

#### Reset Index

In [3]:
pd.concat(
[df1, df2],
ignore_index=True
)  #ignore_index=True resets the row indexes.

    Name
0   Hari
1    Anu
2   Ravi
3  Kiran

#### Horizontal Concatenation

In [4]:
pd.concat(
[df1, df2],
axis=1
)

   Name   Name
0  Hari   Ravi
1   Anu  Kiran

### 2. merge()

In Pandas, merge() is used to combine two DataFrames based on a common column or key, similar to joining tables in SQL

In [15]:
import pandas as pd

df1 = pd.DataFrame({
'EmpID': [1, 2, 3],
'Name': ['Hari', 'Anu', 'Ravi']
})

df2 = pd.DataFrame({
'EmpID': [1, 2, 3],
'Salary': [50000, 60000, 55000]
})

pd.merge(df1,df2, on='EmpID')

   EmpID  Name  Salary
0      1  Hari   50000
1      2   Anu   60000
2      3  Ravi   55000

#### Types of Merge
#### Inner Join (Default)

In [11]:
pd.merge(
df1,
df2,
on='EmpID',
how='inner'
)

   EmpID  Name  Salary
0      1  Hari   50000
1      2   Anu   60000
2      3  Ravi   55000

#### Left Join

In [13]:
pd.merge(
df1,
df2,
on='EmpID',
how='left'
)    #All rows from left DataFrame.

   EmpID  Name  Salary
0      1  Hari   50000
1      2   Anu   60000
2      3  Ravi   55000

#### Right Join

In [ ]:
pd.merge(
df1,
df2,
on='ID',
how='right'
)  #All rows from right DataFrame.

#### Outer Join

In [ ]:
pd.merge(
df1,
df2,
on='ID',
how='outer'
)  #All rows from both DataFrames.

### 3. join()

join() combines DataFrames using their indexes.

It is a convenient method when joining by index instead of columns.

Syntax

df1.join(df2)

In [16]:
df1 = pd.DataFrame({
    'Name': ['Hari', 'Anu']
})

df2 = pd.DataFrame({
    'Salary': [50000, 60000]
})

df1.join(df2)

   Name  Salary
0  Hari   50000
1   Anu   60000

#### Join with Different Types

df1.join(
df2,
how='left'
)

df1.join(
df2,
how='right'
)

df1.join(
df2,
how='outer'
)

### 4. append()

n Pandas, append() was previously used to add rows from one DataFrame to another. DataFrame.append() was removed in Pandas 2.0, so use pd.concat() instead.

#### Deprecated Code

df1.append(df2)

This may produce:

Python
AttributeError:
'DataFrame' object has no attribute 'append'

In [ ]:
import pandas as pd

df1 = pd.DataFrame({
    "Name": ["Hari", "Kumar"]
})

df2 = pd.DataFrame({
    "Name": ["Ravi", "Priya"]
})

result = pd.concat([df1, df2], ignore_index=True)

print(result)

Explanation: pd.concat() combines the rows of both DataFrames into a single DataFrame. ignore_index=True resets the index.

### 5. combine_first()

In Pandas, combine_first() combines two DataFrames by filling missing (NaN) values in the first DataFrame with corresponding non-missing values from the second DataFrame, matching by index and column labels.

In [17]:
import pandas as pd
import numpy as np

df1 = pd.DataFrame({
    "Name": ["Hari", "Kumar", "Ravi"],
    "Salary": [50000, np.nan, 60000]
})

df2 = pd.DataFrame({
    "Name": ["Hari", "Kumar", "Ravi"],
    "Salary": [55000, 40000, 65000]
})

result = df1.combine_first(df2)

print(result)

    Name   Salary
0   Hari  50000.0
1  Kumar  40000.0
2   Ravi  60000.0

Explanation: The missing salary for Kumar is filled with 40000 from df2. Existing non-missing values in df1 are preserved.