## Notebook 13 – Missing Values

### isnull()

The isnull() method is used to identify missing values (NaN, None, NaT) in a DataFrame.

It returns:

True -> Missing Value
False -> Non-Missing Value

In [1]:
import pandas as pd
import numpy as np

df = pd.DataFrame({
    'Name': ['Hari', 'Anu', None],
    'Age': [25, np.nan, 30]
})

df.isnull()

    Name    Age
0  False  False
1  False   True
2   True  False

#### Count Missing Values

In [2]:
df.isnull().sum()

Name    1
Age     1
dtype: int64

#### Total Missing Values

In [4]:

print(df.isnull().sum().sum())

2

#### Filter Rows with Missing Values

To select rows where the Age column contains missing values:

In [5]:
print(df[df["Age"].isnull()])

  Name  Age
1  Anu  NaN

### 2. notnull()

The notnull() function in Pandas is used to check whether values are present (not missing) in a Series or DataFrame.

It returns:

True — if the value is not missing.

False — if the value is missing (NaN, None, or NaT).

**notnull() is the opposite of isnull().**

In [6]:
import pandas as pd

data = [10, None, 30, None, 50]

s = pd.Series(data)

print(s.notnull())

0     True
1    False
2     True
3    False
4     True
dtype: bool

In [7]:
import pandas as pd

data = {
    "Name": ["Hari", "Ravi", None, "Kumar"],
    "Age": [22, None, 25, 24],
    "Salary": [30000, 40000, None, 35000]
}

df = pd.DataFrame(data)

print(df.notnull())

    Name    Age  Salary
0   True   True    True
1   True  False    True
2  False   True   False
3   True   True    True

#### Count Non-Missing Values

Use notnull().sum() to count the non-missing values in each column.

In [8]:
print(df.notnull().sum())

Name      3
Age       3
Salary    3
dtype: int64

#### Filter Rows Using notnull()

Suppose you want to select only rows where the Age column has a value.

In [9]:
print(df[df["Age"].notnull()])

    Name   Age   Salary
0   Hari  22.0  30000.0
2    NaN  25.0      NaN
3  Kumar  24.0  35000.0

### 3. dropna()

The dropna() function in Pandas is used to remove rows or columns that contain missing values, such as NaN, None, or NaT.

#### Removing Rows with Missing Values

In [13]:
import pandas as pd

data = {
    "Name": ["Hari", "Ravi", "Kumar", "Priya"],
    "Age": [22, None, 25, 24],
    "Salary": [30000, 40000, None, 35000]
}

df = pd.DataFrame(data)
print(df)
print("\n",df.dropna())

    Name   Age   Salary
0   Hari  22.0  30000.0
1   Ravi   NaN  40000.0
2  Kumar  25.0      NaN
3  Priya  24.0  35000.0

     Name   Age   Salary
0   Hari  22.0  30000.0
3  Priya  24.0  35000.0

#### dropna(axis=0) — Remove Rows

The axis=0 parameter specifies that you want to remove rows containing missing values.

In [14]:
df.dropna(axis=0)

    Name   Age   Salary
0   Hari  22.0  30000.0
3  Priya  24.0  35000.0

#### dropna(axis=1) — Remove Columns

The axis=1 parameter specifies that you want to remove columns containing missing values.

In [15]:
print(df.dropna(axis=1))

    Name
0   Hari
1   Ravi
2  Kumar
3  Priya

#### dropna(how="any")

Removes a row if at least one value is missing.

In [16]:
print(df.dropna(how="any"))

    Name   Age   Salary
0   Hari  22.0  30000.0
3  Priya  24.0  35000.0

#### dropna(how="all")

Removes a row only when all values in that row are missing.

In [17]:
data = {
    "Name": ["Hari", None, "Kumar"],
    "Age": [22, None, 25],
    "Salary": [30000, None, 35000]
}

df = pd.DataFrame(data)

print(df.dropna(how="all"))

    Name   Age   Salary
0   Hari  22.0  30000.0
2  Kumar  25.0  35000.0

#### dropna(subset=[]) — Check Specific Columns

Use subset when you want to remove rows based on missing values in particular columns.

Example: Remove rows only when the Age value is missing.

In [ ]:
print(df.dropna(subset=["Age"]))

In [ ]:
#You can also check multiple columns:

print(df.dropna(subset=["Age", "Salary"]))

### 4. fillna()

The fillna() function in Pandas is used to replace missing values (NaN, None, or NaT) with a specified value.

Instead of deleting rows containing missing values using dropna(), you can use fillna() to fill those missing values.

#### Fill Missing Values with a Specific Value

In [19]:
import pandas as pd

data = {
    "Name": ["Hari", "Ravi", "Kumar", "Priya"],
    "Age": [22, None, 25, None],
    "Salary": [30000, 40000, None, 35000]
}

df = pd.DataFrame(data)

print(df.fillna(0))

    Name   Age   Salary
0   Hari  22.0  30000.0
1   Ravi   0.0  40000.0
2  Kumar  25.0      0.0
3  Priya   0.0  35000.0

#### Fill Missing Values in a Specific Column

Suppose you want to fill missing values only in the Age column.

In [20]:
df["Age"] = df["Age"].fillna(0)

print(df)

    Name   Age   Salary
0   Hari  22.0  30000.0
1   Ravi   0.0  40000.0
2  Kumar  25.0      NaN
3  Priya   0.0  35000.0

####  Fill Missing Values with Different Values for Different Columns

You can use a dictionary to specify a different replacement value for each column.

In [21]:
df = df.fillna({
    "Age": 18,
    "Salary": 25000
})

print(df)

    Name   Age   Salary
0   Hari  22.0  30000.0
1   Ravi   0.0  40000.0
2  Kumar  25.0  25000.0
3  Priya   0.0  35000.0

#### fillna() with Mean

The mean is the average of the available numerical values.

You can replace missing values with the mean of their column.

In [22]:
import pandas as pd

data = {
    "Name": ["Hari", "Ravi", "Kumar", "Priya"],
    "Age": [22, 24, None, 26]
}

df = pd.DataFrame(data)

df["Age"] = df["Age"].fillna(df["Age"].mean())

print(df)

    Name   Age
0   Hari  22.0
1   Ravi  24.0
2  Kumar  24.0
3  Priya  26.0

#### fillna() with Mode

The mode is the most frequently occurring value.

It is useful for categorical data, such as city, department, or product category.

In [23]:
import pandas as pd

data = {
    "City": ["Chittoor", "Bangalore", "Chittoor", None, "Chittoor", "Bangalore"]
}

df = pd.DataFrame(data)

mode_value = df["City"].mode()[0]

df["City"] = df["City"].fillna(mode_value)

print(df)

        City
0   Chittoor
1  Bangalore
2   Chittoor
3   Chittoor
4   Chittoor
5  Bangalore

#### Forward Fill — ffill()

Forward fill replaces a missing value with the previous available value.

In [24]:
import pandas as pd

data = {
    "Temperature": [30, None, None, 32, None]
}

df = pd.DataFrame(data)

print(df.ffill())

   Temperature
0         30.0
1         30.0
2         30.0
3         32.0
4         32.0

### 5. interpolate()
The interpolate() function in Pandas is used to estimate missing values based on the surrounding available values.

Instead of replacing every missing value with a fixed number, interpolate() calculates an estimated value using a method such as linear interpolation

In [27]:
import pandas as pd

data = {
    "Temperature": [20, None, 30, None, 50]
}

df = pd.DataFrame(data)
print(df)
print("\n",df.interpolate(method="linear"))

   Temperature
0         20.0
1          NaN
2         30.0
3          NaN
4         50.0

    Temperature
0         20.0
1         25.0
2         30.0
3         40.0
4         50.0

#### How Does Linear Interpolation Work?

Estimates missing values using a straight-line relationship between known values.

Linear interpolation assumes that values change at a constant rate between two known points.

- For example, suppose the temperature is:

Day	Temperature

Monday	 20°C

Tuesday	  Missing

Wednesday	30°C

- The temperature increases by 10°C over two days.

Assuming a constant rate of change:

Monday: 20°C

Tuesday: 25°C

Wednesday: 30°C

Pandas estimates Tuesday's temperature as 25°C.

#### Time Interpolation

Estimates missing values based on the actual time intervals between observations.

This method requires a DatetimeIndex.

In [28]:
import pandas as pd

dates = pd.to_datetime([
    "2026-01-01",
    "2026-01-02",
    "2026-01-05"
])

df = pd.DataFrame(
    {"Temperature": [20, None, 40]},
    index=dates
)

print(df.interpolate(method="time"))

            Temperature
2026-01-01         20.0
2026-01-02         25.0
2026-01-05         40.0

#### Polynomial Interpolation

Polynomial interpolation estimates missing values using a polynomial curve rather than a straight line.

In [ ]:
df.interpolate(method="polynomial", order=2)

Here, order=2 specifies a second-degree polynomial.

Note: Polynomial interpolation requires sufficient valid data points. It can also produce unrealistic estimates if the chosen curve does not fit the data well.

### 6. Missing Value Handling Strategies

Missing value handling is an important step in data cleaning and preprocessing. Before using a dataset for data analysis or machine learning, we need to identify missing values and decide how to handle them.

There are several strategies for handling missing values in Pandas.

#### 1.Remove Missing Values

Use dropna() to remove rows containing missing values.

In [30]:
import pandas as pd

df = pd.DataFrame({
    "Name": ["Hari", "Ravi", "Kumar", "Priya"],
    "Age": [22, None, 25, 24],
    "Salary": [30000, 40000, None, 35000]
})

df_cleaned = df.dropna()

print(df_cleaned)

    Name   Age   Salary
0   Hari  22.0  30000.0
3  Priya  24.0  35000.0

#### 2.Fill Missing Values with a Constant

Use fillna() to replace missing values with a fixed value.

In [ ]:
df["Age"] = df["Age"].fillna(0)

print(df)

#### 3.Mean ,median,or mode Imputation

The mean is the average of the available numerical values.

Example:

In [31]:
df = pd.DataFrame({
    "Age": [20, 22, None, 26, 28]
})

df["Age"] = df["Age"].fillna(df["Age"].mean())

print(df)

    Age
0  20.0
1  22.0
2  24.0
3  26.0
4  28.0

#### Forward Fill and Backward Fill

These methods use nearby observations to fill missing values.

Forward Fill — ffill()

Uses the previous available value.

In [32]:
df = pd.DataFrame({
    "Temperature": [30, None, None, 35]
})

print(df.ffill())

   Temperature
0         30.0
1         30.0
2         30.0
3         35.0

In [33]:
print(df.bfill())

   Temperature
0         30.0
1         35.0
2         35.0
3         35.0

#### Interpolation

Interpolation estimates missing numerical values using surrounding observations.

In [34]:

df = pd.DataFrame({
    "Temperature": [20, None, 30, None, 50]
})

df["Temperature"] = df["Temperature"].interpolate()

print(df)

   Temperature
0         20.0
1         25.0
2         30.0
3         40.0
4         50.0

#### Common Missing Value Handling Strategies

| S.No. | Strategy               | Description                                                    | Pandas Function                |
| ----: | ---------------------- | -------------------------------------------------------------- | ------------------------------ |
|     1 | Remove missing rows    | Deletes rows containing missing values                         | `dropna()`                     |
|     2 | Remove missing columns | Deletes columns containing missing values                      | `dropna(axis=1)`               |
|     3 | Fill with a constant   | Replaces missing values with a fixed value                     | `fillna()`                     |
|     4 | Mean imputation        | Replaces missing numerical values with the mean                | `fillna(df["col"].mean())`     |
|     5 | Median imputation      | Replaces missing numerical values with the median              | `fillna(df["col"].median())`   |
|     6 | Mode imputation        | Replaces missing values with the most frequent value           | `fillna(df["col"].mode()[0])`  |
|     7 | Forward fill           | Uses the previous available value                              | `ffill()`                      |
|     8 | Backward fill          | Uses the next available value                                  | `bfill()`                      |
|     9 | Interpolation          | Estimates missing values using surrounding data                | `interpolate()`                |
|    10 | Group-based imputation | Fills missing values using statistics calculated within groups | `groupby()` with `transform()` |
|    11 | Missing indicator      | Creates a column indicating whether a value was missing        | `isnull()`                     |