## Notebook 6 – Data Inspection

### 1.head()

The head() function displays the first few rows of a DataFrame.

By default, it returns the first 5 rows.

In [2]:
import pandas as pd

data = {
    "Name": ["Hari", "Ravi", "Kiran", "Priya", "Arun", "Sneha"],
    "Age": [22, 23, 21, 24, 22, 23],
    "Marks": [85, 90, 78, 95, 88, 92]
}

df = pd.DataFrame(data)

print(df.head())

    Name  Age  Marks
0   Hari   22     85
1   Ravi   23     90
2  Kiran   21     78
3  Priya   24     95
4   Arun   22     88

#### Display a Specific Number of Rows

You can specify how many rows you want to display by passing a number inside head().

In [5]:
#Display the First 3 Rows
df.head(3)

    Name  Age  Marks
0   Hari   22     85
1   Ravi   23     90
2  Kiran   21     78

### 2.tail()

The tail() function displays the last few rows of a DataFrame.

By default, it returns the last 5 rows.

#### Example

In [4]:
df.tail()

    Name  Age  Marks
1   Ravi   23     90
2  Kiran   21     78
3  Priya   24     95
4   Arun   22     88
5  Sneha   23     92

#### Show Last N Rows

In [6]:
df.tail(2)

    Name  Age  Marks
4   Arun   22     88
5  Sneha   23     92

### 3.sample()

The sample() function returns random rows from a DataFrame.

The sample() method in Pandas is used to select random rows or columns from a DataFrame or Series.

Unlike head(), which displays the first rows, or tail(), which displays the last rows, sample() selects data randomly.

Useful for quickly inspecting large datasets.

#### Example

In [8]:
print(df.sample())

    Name  Age  Marks
2  Kiran   21     78

#### Select Multiple Random Rows

You can specify how many random rows you want using the n parameter.

In [9]:
print(df.sample(n=3))

   Name  Age  Marks
1  Ravi   23     90
0  Hari   22     85
4  Arun   22     88

#### Select Random Rows Using frac

Instead of specifying the exact number of rows, you can specify the fraction of the dataset to select.

In [10]:
#Example 1: Select 50% of the Rows
print(df.sample(frac=0.5))

    Name  Age  Marks
2  Kiran   21     78
3  Priya   24     95
5  Sneha   23     92

### 4.info()

The info() function provides a summary of the DataFrame.

The info() method in Pandas provides a concise summary of a DataFrame, including its number of rows, column names, non-null value counts, data types, and memory usage.

It is useful when you want to understand the structure of a dataset before performing data analysis.

#### Example

In [11]:
import pandas as pd

data = {
    "Name": ["Hari", "Ravi", "Kiran", "Priya", "Arun"],
    "Age": [22, 23, 21, 24, 22],
    "Marks": [85, 90, 78, 95, 88]
}

df = pd.DataFrame(data)

df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    5 non-null      str
 1   Age     5 non-null      int64
 2   Marks   5 non-null      int64
dtypes: int64(2), str(1)
memory usage: 274.0 bytes

In [12]:
import pandas as pd

data = {
    "Name": ["Hari", "Ravi", None, "Priya"],
    "Age": [22, 23, 21, None],
    "Marks": [85, 90, 78, 95]
}

df = pd.DataFrame(data)

df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    3 non-null      str
 1   Age     3 non-null      float64
 2   Marks   4 non-null      int64
dtypes: float64(1), int64(1), str(1)
memory usage: 242.0 bytes

### 5.describe()

The describe() function generates descriptive statistics for numerical columns.

By default, describe() calculates statistics for numeric columns in a DataFrame.

The describe() method in Pandas is used to generate descriptive statistics that summarize the data in a DataFrame or Series.

It helps you understand your dataset by calculating statistical measures such as:

Count
Mean
Standard deviation
Minimum value
Maximum value
Quartiles (25%, 50%, and 75%)

#### Example

In [13]:
print(df.describe())

        Age     Marks
count   3.0   4.00000
mean   22.0  87.00000
std     1.0   7.25718
min    21.0  78.00000
25%    21.5  83.25000
50%    22.0  87.50000
75%    22.5  91.25000
max    23.0  95.00000

#### Notice: The Name column is not included because it contains text. By default, describe() summarizes numeric columns.

#### Describe Specific Columns

Suppose you want to calculate statistics only for the Marks column.

In [14]:
print(df["Marks"].describe())

count     4.00000
mean     87.00000
std       7.25718
min      78.00000
25%      83.25000
50%      87.50000
75%      91.25000
max      95.00000
Name: Marks, dtype: float64

#### Describe All Columns, Including Text

By default, describe() summarizes numeric columns.

If you want to include text columns as well, use:

In [15]:
print(df.describe(include="all"))

        Name   Age     Marks
count      3   3.0   4.00000
unique     3   NaN       NaN
top     Hari   NaN       NaN
freq       1   NaN       NaN
mean     NaN  22.0  87.00000
std      NaN   1.0   7.25718
min      NaN  21.0  78.00000
25%      NaN  21.5  83.25000
50%      NaN  22.0  87.50000
75%      NaN  22.5  91.25000
max      NaN  23.0  95.00000

### 6.shape

The shape attribute in Pandas returns the number of rows and columns in a DataFrame.

It returns a tuple containing two values:

In [18]:
print(df.shape)

(4, 3)

#### Get Only the Number of Rows

You can access the first value of the tuple using index 0.

In [19]:
df.shape[0]

4

#### Get Only the Number of Columns

You can access the second value using index 1.

In [20]:
df.shape[1]

3

### 7.columns

The columns attribute in Pandas is used to display the names of all columns in a DataFrame.

For example, if a DataFrame contains Name, Age, and Marks, the columns attribute returns those column names.

Remember: columns is an attribute, not a method. Therefore, use df.columns, not df.columns().

In [24]:
df.columns

Index(['Name', 'Age', 'Marks'], dtype='str')

#### Convert Column Names into a List

Sometimes you may want the column names as a regular Python list.

You can use the tolist() method.

In [23]:
df.columns.tolist()

['Name', 'Age', 'Marks']

#### Access a Specific Column Name

You can access individual column names using indexing.

In [25]:
#First Column
df.columns[0]

'Name'

#### Rename Columns

You can rename columns using the rename() method.

In [27]:
df.rename(
    columns={"Name": "Student_Name", "Marks": "Student_Marks"},
    inplace=True
)

print(df.columns)

Index(['Student_Name', 'Age', 'Student_Marks'], dtype='str')

#### Explanation
"Name" is renamed to "Student_Name".

"Marks" is renamed to "Student_Marks".

inplace=True applies the changes directly to df.

Only the specified column names are changed. The other column names remain the same.

#### Check Whether a Column Exists

You can use the in operator to check whether a column name exists.

In [28]:
print("Age" in df.columns)

True

#### Select Multiple Columns by names

In [29]:
print(df[["Student_Name", "Student_Marks"]])

  Student_Name  Student_Marks
0         Hari             85
1         Ravi             90
2          NaN             78
3        Priya             95

### 8. dtypes

The dtypes attribute displays the data type of each column in a DataFrame.

In [38]:
df.dtypes

Student_Name         str
Age              float64
Student_Marks      int64
dtype: object

#### Check Data Type of a Single Column

In [39]:
df['Age'].dtype

dtype('float64')

In [40]:
df['Student_Marks'].dtype

dtype('int64')

### 9.memory_usage()

The memory_usage() function shows how much memory each column consumes.

It helps identify columns that take large amounts of memory.

By default, it returns the memory usage of each column in bytes, including the DataFrame's index.

In [42]:
df.memory_usage()

Index            132
Student_Name      46
Age               32
Student_Marks     32
dtype: int64

- Index represents the memory used by the DataFrame's index.
- Name represents the memory attributed to that column's underlying data.
- Age represents the memory attributed to the age values.
- Marks represents the memory attributed to the marks values.

Important: By default, Pandas does not include the full memory consumed by Python objects stored in object-type columns. We can request a deeper estimate using deep=True.

#### Understanding deep=True

When a column contains strings or other Python objects, the default memory calculation may not include the memory used by the objects themselves.

Use deep=True for a more comprehensive estimate.

Include Actual Object Memory

For string columns:

In [43]:
print(df.memory_usage(deep=True))

Index            132
Student_Name      46
Age               32
Student_Marks     32
dtype: int64

#### total mem usage

In [44]:
total_memory = df.memory_usage(deep=True).sum()

print("Total memory usage:", total_memory, "bytes")

Total memory usage: 242 bytes

#### Display Memory Usage in Kilobytes

Memory usage is often easier to understand in kilobytes (KB).

You can divide the total number of bytes by 1024.

In [45]:
total_memory = df.memory_usage(deep=True).sum()

memory_kb = total_memory / 1024

print("Total memory usage:", round(memory_kb, 2), "KB")

Total memory usage: 0.24 KB

### 10.nunique()

In Pandas, nunique() is used to count the number of unique (distinct) values in a Series or DataFrame column.

In simple words, it tells you how many different values exist in a column, without counting repeated values multiple times.

In [56]:
import pandas as pd

data = {
    "Student": ["Ravi", "Priya", "Kumar", "Sneha", "Arun"],
    "Department": ["CSE", "ECE", "CSE", "IT", "ECE"]
}

df = pd.DataFrame(data)

print(df)

print("\n",df.nunique())

  Student Department
0    Ravi        CSE
1   Priya        ECE
2   Kumar        CSE
3   Sneha         IT
4    Arun        ECE

 Student       5
Department    3
dtype: int64

#### single column

In [55]:

print("\n Number of unique departments:", df["Department"].nunique())

 Number of unique departments: 3

### 11.value_counts()

In Pandas, value_counts() counts how many times each unique value appears in a column.

The value_counts() function counts the frequency of each unique value in a column.

In [57]:
df = pd.DataFrame({
    'Department': [
        'IT',
        'HR',
        'IT',
        'Finance',
        'IT',
        'HR'
    ]
})

print(df['Department'].value_counts())

Department
IT         3
HR         2
Finance    1
Name: count, dtype: int64

#### Include Percentage Distribution

In [58]:

df['Department'].value_counts(normalize=True)

Department
IT         0.500000
HR         0.333333
Finance    0.166667
Name: proportion, dtype: float64

#### Include Missing Values

In [59]:
df['Department'].value_counts(dropna=False)

Department
IT         3
HR         2
Finance    1
Name: count, dtype: int64