## Notebook 7 – Selecting & Filtering Dat

### 1. loc

In Pandas, loc[] is used to access and select rows and columns of a DataFrame using their labels.

In simple words, loc[] helps you retrieve specific data from a DataFrame by specifying row labels and column names

loc (label-based location) is used to select rows and columns using row labels and column names.

Syntax of loc[]

df.loc[row_label , column_label]

#### example

In [32]:
import pandas as pd

data = {
    "Name": ["Ravi", "Priya", "Kumar", "Sneha", "Arun"],
    "Age": [22, 23, 21, 24, 22],
    "Department": ["CSE", "ECE", "IT", "CSE", "ECE"],
    "Salary": [30000, 35000, 28000, 40000, 32000]
}

df = pd.DataFrame(data)

print(df)

    Name  Age Department  Salary
0   Ravi   22        CSE   30000
1  Priya   23        ECE   35000
2  Kumar   21         IT   28000
3  Sneha   24        CSE   40000
4   Arun   22        ECE   32000

#### Selecting a Single Row Using loc[]

In [33]:
print(df.loc[0])

Name           Ravi
Age              22
Department      CSE
Salary        30000
Name: 0, dtype: object

#### Selecting a Specific Value Using loc[]

In [34]:
print(df.loc[1,"Age"])

23

#### Selecting Multiple Rows Using loc[]

Suppose you want to retrieve the rows labeled 0, 1, and 2.

In [35]:
print(df.loc[0:2])    #here the last value is also included

    Name  Age Department  Salary
0   Ravi   22        CSE   30000
1  Priya   23        ECE   35000
2  Kumar   21         IT   28000

#### Selecting Multiple specific Rows

In [36]:
print(df.loc[[0,2,4,]])

    Name  Age Department  Salary
0   Ravi   22        CSE   30000
2  Kumar   21         IT   28000
4   Arun   22        ECE   32000

#### Selecting Specific Columns

In [37]:
print(df.loc[:,"Name"])

0     Ravi
1    Priya
2    Kumar
3    Sneha
4     Arun
Name: Name, dtype: str

In [38]:
print(df.loc[:,["Name","Age"]])

    Name  Age
0   Ravi   22
1  Priya   23
2  Kumar   21
3  Sneha   24
4   Arun   22

#### Selecting Specific Rows and Columns Together

In [39]:
print(df.loc[[0,2],["Name","Age"]])

    Name  Age
0   Ravi   22
2  Kumar   21

#### Filtering Rows Using Conditions with loc[]

In [40]:
print(df.loc[df["Age"] > 22])

    Name  Age Department  Salary
1  Priya   23        ECE   35000
3  Sneha   24        CSE   40000

In [41]:
import pandas as pd

data = {
    "Name": ["Hari", "Ravi", "Kumar", "Sneha"],
    "Age": [22, 24, 25, 23]
}

df2 = pd.DataFrame(data)

print(df2.loc[(df["Age"] > 22) & (df2["Name"] == "Kumar")])

Empty DataFrame
Columns: [Name, Age]
Index: []

#### Updating Values Using loc[]

In [30]:
df.loc[0,"Salary"] = 52348
print(df)

    Name  Age   Salary
0   Hari   22  52348.0
1   Ravi   24      NaN
2  Kumar   25      NaN
3  Sneha   23      NaN

In [ ]:
df.loc[df["Salary"] < 30000, "Salary"] = 30000

print(df)

#Pandas identifies rows where the salary is below 30000 and updates only those salary values.

### 2.iloc

iloc (integer location) is used to select rows and columns using integer positions (indexes).

#### Example

In [42]:
import pandas as pd

data = {
    "Name": ["Hari", "Kumar", "Ravi", "Priya"],
    "Age": [22, 25, 23, 24],
    "City": ["Chittoor", "Chennai", "Bangalore", "Hyderabad"]
}

df = pd.DataFrame(data)

print(df)

    Name  Age       City
0   Hari   22   Chittoor
1  Kumar   25    Chennai
2   Ravi   23  Bangalore
3  Priya   24  Hyderabad

#### Select a single row

In [43]:
print(df.iloc[0])

Name        Hari
Age           22
City    Chittoor
Name: 0, dtype: object

#### Select a single value

Syntax:

df.iloc[row_position, column_position]

In [47]:
print(df.iloc[1,0])

# 1 → Second row.
# 0 → First column (Name).

Kumar

#### Select multiple rows

In [48]:
print(df.iloc[0:2])   #here the last value is not included

    Name  Age      City
0   Hari   22  Chittoor
1  Kumar   25   Chennai

#### Select specific rows

In [49]:
print(df.iloc[[0, 2]])

   Name  Age       City
0  Hari   22   Chittoor
2  Ravi   23  Bangalore

#### Select specific columns

In [50]:
print(df.iloc[:, 0])

0     Hari
1    Kumar
2     Ravi
3    Priya
Name: Name, dtype: str

#### Select multiple specific columns

In [51]:
print(df.iloc[:,[0,1]])

    Name  Age
0   Hari   22
1  Kumar   25
2   Ravi   23
3  Priya   24

#### Select specific rows and columns

In [52]:
print(df.iloc[0:3, 0:2])  #last values are not included

    Name  Age
0   Hari   22
1  Kumar   25
2   Ravi   23

#### Select the last row

In [53]:
print(df.iloc[-1])

Name        Priya
Age            24
City    Hyderabad
Name: 3, dtype: object

####  Select the last two rows

In [54]:
print(df.iloc[-2:])

    Name  Age       City
2   Ravi   23  Bangalore
3  Priya   24  Hyderabad

### 3. Boolean Indexing

Boolean Indexing is a technique in Pandas used to filter rows from a DataFrame based on a condition.

It returns only the rows where the condition evaluates to True.

df["Age"] > 22

This checks the age of every employee and returns True or False.

True → The condition is satisfied.

False → The condition is not satisfied.

#### Example

In [67]:
import pandas as pd

data = {
    "Name": ["Hari", "Kumar", "Ravi", "Priya", "Suresh"],
    "Age": [22, 25, 23, 20, 28],
    "Salary": [25000, 35000, 30000, 22000, 45000],
    "City": ["Chittoor", "Chennai", "Bangalore", "Hyderabad", "Chennai"]
}

df = pd.DataFrame(data)

print(df)

     Name  Age  Salary       City
0    Hari   22   25000   Chittoor
1   Kumar   25   35000    Chennai
2    Ravi   23   30000  Bangalore
3   Priya   20   22000  Hyderabad
4  Suresh   28   45000    Chennai

#### Apply a Boolean Condition

In [58]:
print(df["Age"] > 22)

0    False
1     True
2     True
3    False
4     True
Name: Age, dtype: bool

#### Filter the DataFrame Using Boolean Indexing

To retrieve only the employees whose age is greater than 22:

In [59]:
df[df["Age"] > 22]

     Name  Age  Salary       City
1   Kumar   25   35000    Chennai
2    Ravi   23   30000  Bangalore
4  Suresh   28   45000    Chennai

#### Select employees whose age is greater than 22 AND whose salary is greater than 30000.

In [60]:
print(df[(df["Age"] > 22) & (df["Salary"] > 30000)])

     Name  Age  Salary     City
1   Kumar   25   35000  Chennai
4  Suresh   28   45000  Chennai

#### Select employees whose age is greater than 25 OR whose salary is greater than 40000.

In [61]:
print(df[(df["Age"] > 25) | (df["Salary"] > 40000)])

     Name  Age  Salary     City
4  Suresh   28   45000  Chennai

#### Select employees whose age is  not greater than 22.

In [62]:
print(df[~(df["Age"] > 22)])

    Name  Age  Salary       City
0   Hari   22   25000   Chittoor
3  Priya   20   22000  Hyderabad

### 4. Filtering Rows

Filtering rows means selecting only those rows that satisfy specific conditions.

This is one of the most common operations in data analysis.

#### Filter by Single Condition

In [70]:
df[df['Age'] > 25]

     Name  Age  Salary     City
4  Suresh   28   45000  Chennai

#### Filter by City

In [71]:
df[df['City'] == 'Mumbai']

Empty DataFrame
Columns: [Name, Age, Salary, City]
Index: []

#### Using AND (&)

Filter employees whose age is greater than 22 and salary is greater than 30000.

In [72]:
print(df[(df["Age"] > 22) & (df["Salary"] > 30000)])

     Name  Age  Salary     City
1   Kumar   25   35000  Chennai
4  Suresh   28   45000  Chennai

#### Using OR (|)

Filter employees whose age is less than 22 or salary is greater than 40000.

In [73]:
print(df[(df["Age"] < 22) | (df["Salary"] > 40000)])

     Name  Age  Salary       City
3   Priya   20   22000  Hyderabad
4  Suresh   28   45000    Chennai

#### Using NOT (~)

Filter employees whose age is not greater than 22.

In [74]:
print(df[~(df["Age"] > 22)])

    Name  Age  Salary       City
0   Hari   22   25000   Chittoor
3  Priya   20   22000  Hyderabad

#### Filter Rows Using isin()

The isin() method filters rows when a column contains any value from a specified list.

**Select employees who live in Chennai or Hyderabad.**

In [76]:
print(df[df["City"].isin(["Chennai", "Hyderabad"])])

     Name  Age  Salary       City
1   Kumar   25   35000    Chennai
3   Priya   20   22000  Hyderabad
4  Suresh   28   45000    Chennai

In [77]:
print(df[df["Age"].isin([22, 25, 28])])  #This selects employees whose ages are 22, 25, or 28.

     Name  Age  Salary      City
0    Hari   22   25000  Chittoor
1   Kumar   25   35000   Chennai
4  Suresh   28   45000   Chennai

#### Filter Rows Using between()

The between() method selects rows where values fall within a specified range. Both endpoints are included by default.

**Select employees whose age is between 22 and 25.**

In [78]:
print(df[df["Age"].between(22, 25)])  #This selects employees aged 22, 23, 24, or 25, if those ages exist in the DataFrame.

    Name  Age  Salary       City
0   Hari   22   25000   Chittoor
1  Kumar   25   35000    Chennai
2   Ravi   23   30000  Bangalore

#### Filter Rows Based on Missing Values

Pandas provides isna() and notna() to filter rows based on missing values.

These methods are useful when cleaning datasets.

In [80]:
# Rows where Salary is missing
print(df[df["Salary"].isna()])

Empty DataFrame
Columns: [Name, Age, Salary, City]
Index: []

In [81]:
# Rows where Salary is not missing
print(df[df["Salary"].notna()])

     Name  Age  Salary       City
0    Hari   22   25000   Chittoor
1   Kumar   25   35000    Chennai
2    Ravi   23   30000  Bangalore
3   Priya   20   22000  Hyderabad
4  Suresh   28   45000    Chennai

### 5.query()

In Pandas, the query() method is used to filter rows from a DataFrame by writing conditions inside a string.

It provides an alternative to Boolean indexing and can make filtering code easier to read

Syntax

df.query('condition')

In [82]:
print(df.query("Age > 22"))

     Name  Age  Salary       City
1   Kumar   25   35000    Chennai
2    Ravi   23   30000  Bangalore
4  Suresh   28   45000    Chennai

#### Use Multiple Conditions in query()

You can combine multiple conditions using and, or, and not.

- Example 1: Using and

Select employees whose age is greater than 22 and salary is greater than ₹30,000.

In [83]:
print(df.query("Age > 22 and Salary > 30000"))

     Name  Age  Salary     City
1   Kumar   25   35000  Chennai
4  Suresh   28   45000  Chennai

#### Filter Rows Using String Columns

You can filter rows using text values as well as numerical values.

Example 1: Select employees from Chennai

In [ ]:
print(df.query("City == 'Chennai'"))

### 6. isin()

In [ ]:
The isin() method checks whether values belong to a specified list.

It returns a Boolean Series (True or False).

In [85]:
df["Age"].isin([23,25,28])

0    False
1     True
2     True
3    False
4     True
Name: Age, dtype: bool

#### Filter Rows using isin()

In [86]:
df[df['City'].isin(['Chennai', 'Bangalore'])]

     Name  Age  Salary       City
1   Kumar   25   35000    Chennai
2    Ravi   23   30000  Bangalore
4  Suresh   28   45000    Chennai

#### Opposite of isin()

Use ~ (NOT operator).

In [88]:
df[~df['City'].isin(['Chennai'])]

    Name  Age  Salary       City
0   Hari   22   25000   Chittoor
2   Ravi   23   30000  Bangalore
3  Priya   20   22000  Hyderabad

### 7. between()

In Pandas, between() is used to check whether values in a Series fall within a specified range. It returns True for values within the range and False for values outside it.

The between() method checks whether values lie within a specified range.

Both boundary values are included by default.

df['column'].between(start, end)

In [89]:
df = pd.DataFrame({
    'Age': [18, 22, 25, 30, 35]
})

df['Age'].between(20, 30)

0    False
1     True
2     True
3     True
4    False
Name: Age, dtype: bool

#### Filter Rows using between()

In [90]:
df[df['Age'].between(20, 30)]

   Age
1   22
2   25
3   30

#### 8.Sorting Data

Sorting arranges data in ascending or descending order.

In Pandas, sorting data means arranging rows in a particular order based on the values in one or more columns.

Pandas provides two important methods for sorting:

- sort_values() — Sort rows based on column values.
- sort_index() — Sort rows or columns based on their index labels.

#### sort_values()

The sort_values() method sorts a DataFrame according to the values in a specified column or columns.

Syntax

df.sort_values(by="column_name", ascending=True)

Parameters:

by — Specifies the column or columns used for sorting.
    
ascending=True — Sorts from smallest to largest or A to Z.
    
ascending=False — Sorts from largest to smallest or Z to A.

**example**

In [95]:
print(df.sort_values(by="Age"))

   Age
0   18
1   22
2   25
3   30
4   35

**Sort by Age in Descending Order**

In [92]:
print(df.sort_values(by="Age", ascending=False))

   Age
4   35
3   30
2   25
1   22
0   18

#### Sort Using Multiple Columns

City → Ascending.

Age → Descending.

Important: Each value in ascending corresponds to the column in the same position in by.

In [ ]:
print(df.sort_values(by=["City", "Age"], ascending=[True, False]))

#### sort_index()

The sort_index() method sorts a DataFrame based on its index labels rather than the values in a column.

In [96]:
print(df.sort_index())

   Age
0   18
1   22
2   25
3   30
4   35

This arranges the rows according to index labels from smallest to largest.

Our original DataFrame is already in this order, so the output remains unchanged.

#### Sort by Index in Descending Order

In [97]:
print(df.sort_index(ascending=False))

   Age
4   35
3   30
2   25
1   22
0   18

#### Sort Columns by Their Names

In [98]:
print(df.sort_index(axis=1))

#Here, axis=1 sorts the column labels alphabetically.

   Age
0   18
1   22
2   25
3   30
4   35

In [ ]:
axis=0 → Sort rows by their index labels.
    
axis=1 → Sort columns by their labels.