## Notebook 8 – Data Manipulation

### 1. Rename Columns

Renaming columns means changing existing column names to more meaningful or convenient names.

Syntax

df.rename(columns={'old_name':'new_name'})

### Example

In [1]:
import pandas as pd
 
df = pd.DataFrame({
'Name': ['Hari', 'Anu'],
'Age': [25, 28]
})
 
df_new = df.rename(
columns={'Name': 'Employee_Name'}
)
 
print(df_new)

  Employee_Name  Age
0          Hari   25
1           Anu   28

In [2]:
df.rename(
columns={
'Name': 'Employee_Name',
'Age': 'Employee_Age'
}
)

  Employee_Name  Employee_Age
0          Hari            25
1           Anu            28

#### Rename Columns Permanently

In [5]:
df.rename(
columns={'Name':'Employee_Name'},
inplace=True
)

### 2. Drop Rows

In [ ]:
Dropping rows means removing unwanted rows from a DataFrame.

syntax:

df.drop(row_index)

In [ ]:
df = pd.DataFrame({
    'Name': ['Hari', 'Anu', 'Ravi'],
    'Age': [25, 28, 22]
})

df.drop(1)

#### Drop Multiple Rows

In [ ]:
df.drop([0, 2])

#### Drop Rows Permanently

In [ ]:
df.drop(
1,
inplace=True
)

#### Drop Rows Based on Condition

In [ ]:
df = df[df['Age'] > 25]

### 3. Drop Columns

In [ ]:
Dropping columns means removing one or more columns from a DataFrame.

In [ ]:
df.drop(
    'column_name',
    axis=1
)

In [ ]:
axis=1 indicates column operation.

#### Example

In [2]:
import pandas as pd
df = pd.DataFrame({
'Name': ['Hari', 'Anu'],
'Age': [25, 28],
'City': ['Hyderabad', 'Delhi']
})
 
df.drop(
'City',
axis=1
)

   Name  Age
0  Hari   25
1   Anu   28

#### Drop Multiple Columns

In [3]:
df.drop(
['Age', 'City'],
axis=1
)

   Name
0  Hari
1   Anu

### 4. Insert Columns

Inserting columns means adding a new column at a specified position in the DataFrame.

syntax;

df.insert(loc, column, value)

| Parameter | Description                                               |
| --------- | --------------------------------------------------------- |
| `loc`     | Integer position where the new column should be inserted. |
| `column`  | Name of the new column.                                   |
| `value`   | Values to insert into the column.                         |

Remember: Column positions start from 0.

#### Example 1: Insert a column at the end

In [ ]:
df.insert(3, "Salary", [25000, 35000, 30000, 28000])

print(df)

- Explanation:

3 → Insert at the fourth position.
    
"Salary" → Name of the new column.
    
[25000, 35000, 30000, 28000] → Values for the four rows.

#### Insert a column using a single value

You can insert the same value into every row.

Every row receives "India" in the Country column

In [ ]:
df.insert(2, "Country", "India")

print(df)

#### Insert a column using a calculated value

You can calculate values from existing columns and insert the result.

In [ ]:
df.insert(2, "Age_Next_Year", df["Age"] + 1)

print(df)

#### Difference Between insert() and Direct Assignment

You can also create columns using direct assignment.

**Using insert()**

**df.insert(1, "Bonus", [1000, 2000, 1500, 1800])**

This inserts Bonus at position 1.

**Using direct assignment**

**df["Bonus"] = [1000, 2000, 1500, 1800]**

This creates Bonus at the end if it does not exist. If the column already exists, it replaces its values.

### 5. assign()

The assign() method is used to create new columns or modify existing columns without changing the original DataFrame.

It returns a new DataFrame.

**Important: Unlike insert(), the assign() method returns a new DataFrame and does not modify the original DataFrame.**

- Syntax

df.assign(column_name=value)

In [5]:
import pandas as pd

data = {
    "Name": ["Hari", "Kumar", "Ravi", "Priya"],
    "Age": [22, 25, 23, 24],
    "Salary": [25000, 35000, 30000, 40000]
}

df = pd.DataFrame(data)

print(df)

    Name  Age  Salary
0   Hari   22   25000
1  Kumar   25   35000
2   Ravi   23   30000
3  Priya   24   40000

#### Create a New Column Using assign()

In [6]:
n_df=df.assign(Bonus=[2000, 3000, 2500, 4000])
print(n_df)

    Name  Age  Salary  Bonus
0   Hari   22   25000   2000
1  Kumar   25   35000   3000
2   Ravi   23   30000   2500
3  Priya   24   40000   4000

#### Create a Column Using an Existing Column

You can calculate new column values from existing columns.

In [ ]:
new_df = df.assign(Next_Year_Age=df["Age"] + 1)

print(new_df)

#### Create Multiple Columns Using assign()

You can create several columns in a single operation.

In [ ]:
new_df = df.assign(
    Annual_Salary=df["Salary"] * 12,
    Bonus=df["Salary"] * 0.10,
    Next_Year_Age=df["Age"] + 1
)

print(new_df)

#### Modify an Existing Column Using assign()

If the specified column already exists, assign() replaces its values in the returned DataFrame.

In [ ]:
new_df = df.assign(Age=df["Age"] + 5)

print(new_df)

#### Store the Result Back in the Original Variable

Although assign() does not modify the original DataFrame directly, you can reassign its result.

In [ ]:
df = df.assign(Bonus=df["Salary"] * 0.10)

print(df)

### 6. apply()

In Pandas, apply() is used to apply a function to the values of a Series or along the rows or columns of a DataFrame.

**It is useful when built-in Pandas functions are not enough.** 

- Syntax

df['column'].apply(function)

#### Using apply() on a Series

A Series is a single column of a DataFrame.

When you call apply() on a Series, the function is generally applied to each value individually.

**Example 1: Increase Every Salary by 10%**

In [ ]:
df["Salary"].apply(lambda x: x * 1.10)

**Important: This expression returns the calculated Series but does not change the original Salary column.**

**To save the updated salaries:**

In [ ]:
df["Salary"] = df["Salary"].apply(lambda x: x * 1.10)

#### Convert Text to Uppercase

In [7]:
df = pd.DataFrame({
    'Name': ['hari', 'anu', 'ravi']
})

df['Name'].apply(str.upper)

0    HARI
1     ANU
2    RAVI
Name: Name, dtype: str

#### Custom Function

In [16]:
import pandas as pd

df=pd.DataFrame({
    "Age":[22,23,17,15,73,19]
})

def category(age):
    if age >= 25: 
        return "Adult"
    else: 
        return "Young"
 
df['Age_Group'] = df['Age'].apply(category)

print(df)

   Age Age_Group
0   22     Young
1   23     Young
2   17     Young
3   15     Young
4   73     Adult
5   19     Young

#### Using apply() on DataFrame Rows

So far, we have applied functions to individual columns.

You can also use apply() on an entire DataFrame to process rows or columns.

The axis parameter determines the direction.

Parameter	           Meaning

axis=0	     Apply the function to each column

axis=1	     Apply the function to each row

Remember:

axis=0 → Work down the rows, processing each column.

axis=1 → Work across the columns, processing each row.

In [18]:
df2 = pd.DataFrame({
    "Name": ["Hari", "Kumar", "Ravi"],
    "Salary": [25000, 35000, 30000],
    "Bonus": [2000, 3000, 2500]
})

#### Now calculate total compensation for each employee.

In [19]:
df2["Total"] = df2.apply(
    lambda row: row["Salary"] + row["Bonus"],
    axis=1
)

print(df2)

    Name  Salary  Bonus  Total
0   Hari   25000   2000  27000
1  Kumar   35000   3000  38000
2   Ravi   30000   2500  32500

#### Using apply() on Columns

You can also apply a function to each column by specifying axis=0.

For example, calculate the maximum value of each numeric column:

In [ ]:
print(df[["Age", "Salary", "Marks"]].apply(max, axis=0))

### 7. map()

In [ ]:
In Pandas, map() is used to transform or replace values in a Series (usually a DataFrame column) using a function, dictionary, or another Series.

It is useful when you want to:

Replace values with new values.
    
Convert text to uppercase or lowercase.

Map categories to numerical values.
    
Apply a function to every value in a column.
    
Prepare data for Machine Learning.

#### example:
- Suppose you have a column containing student grades:

| Student | Grade |
| ------- | ----- |
| Hari    | A     |
| Kumar   | B     |
| Ravi    | A     |
| Priya   | C     |

In [ ]:
You want to convert the grades into numerical values:

A → 90
B → 80
C → 70

You can use map() to perform this conversion.

df["Grade"].map({"A": 90, "B": 80, "C": 70})

#### Example Map Using Dictionary

In [25]:
df = pd.DataFrame({
    'Gender': ['M', 'F', 'M', 'F']
})

mapping = {
    'M': 'Male',
    'F': 'Female'
}

df["Gender"]=df['Gender'].map(mapping)
print(df)

   Gender
0    Male
1  Female
2    Male
3  Female

#### Using map() with a Function

In [24]:
df['Gender'].map(str.lower)

0      male
1    female
2      male
3    female
Name: Gender, dtype: str

### 8. replace()

In [ ]:
In Pandas, replace() is used to replace existing values in a Series or DataFrame with new values.

In [26]:
import pandas as pd

data = {
    "Name": ["Hari", "Kumar", "Ravi", "Priya", "Suresh"],
    "Age": [22, 25, 23, 20, 28],
    "Salary": [25000, 35000, 30000, 22000, 45000],
    "Department": ["IT", "HR", "IT", "Finance", "HR"]
}

df = pd.DataFrame(data)

print(df)

     Name  Age  Salary Department
0    Hari   22   25000         IT
1   Kumar   25   35000         HR
2    Ravi   23   30000         IT
3   Priya   20   22000    Finance
4  Suresh   28   45000         HR

In [ ]:
#### Replace a Single Value

The simplest use of replace() is to replace one value with another.

Example 1: Replace "IT" with "Technology"

In [30]:
print(df["Department"].replace("IT","Technology"))

0    Technology
1            HR
2    Technology
3       Finance
4            HR
Name: Department, dtype: str

#### Replace Multiple Values Using a Dictionary

In [31]:
print(
    df["Department"].replace({
        "IT": "Technology",
        "HR": "Human Resources",
        "Finance": "Finance Department"
    })
)

0            Technology
1       Human Resources
2            Technology
3    Finance Department
4       Human Resources
Name: Department, dtype: str

#### Replace Values in the Entire DataFrame

You can also use replace() directly on a DataFrame.

**Example 1: Replace a Value Across the DataFrame**

In [32]:
print(df.replace("IT", "Technology"))

#This replaces matching "IT" values throughout the DataFrame, rather than only in the Department column.

     Name  Age  Salary  Department
0    Hari   22   25000  Technology
1   Kumar   25   35000          HR
2    Ravi   23   30000  Technology
3   Priya   20   22000     Finance
4  Suresh   28   45000          HR

**Example 2: Replace Multiple Values Across the DataFrame**

In [ ]:
print(df.replace({
    "IT": "Technology",
    "HR": "Human Resources"
}))

#This replaces matching values wherever they occur in the DataFrame.

#### Replace Values and Update the Original DataFrame

By default, replace() does not modify the original DataFrame.

To save the result, assign it back to the column.

In [ ]:
df["Department"] = df["Department"].replace({
    "IT": "Technology",
    "HR": "Human Resources",
    "Finance": "Finance Department"
})

print(df)

### 9. Duplicate Handling

Duplicate handling involves identifying and removing repeated records from a DataFrame.

Pandas provides four important methods for duplicate handling:

- duplicated() — Identifies duplicate rows.
- drop_duplicates() — Removes duplicate rows.
- keep parameter — Controls which occurrence to retain.
- subset parameter — Checks duplicates using specific columns.

#### duplicated()

The duplicated() method identifies duplicate rows and returns a Boolean Series containing True or False.

In [34]:
df = pd.DataFrame({
    'Name': ['Hari', 'Anu', 'Hari'],
    'Age': [25, 28, 25]
})

df.duplicated()

0    False
1    False
2     True
dtype: bool

| Parameter      | Description                                                  |
| -------------- | ------------------------------------------------------------ |
| `subset`       | Specifies the column or columns used to identify duplicates. |
| `keep="first"` | Marks all occurrences as duplicates except the first.        |
| `keep="last"`  | Marks all occurrences as duplicates except the last.         |
| `keep=False`   | Marks every occurrence of a duplicated record as `True`.     |

#### Display Only Duplicate Rows

Suppose you want to see the actual records that are duplicated.

In [35]:
df[df.duplicated()]

   Name  Age
2  Hari   25

#### Count Duplicate Rows

In [39]:
print(df.duplicated().sum())

1

#### Identify All Occurrences of Duplicates

By default, the first occurrence is not marked as a duplicate.

If you want to mark every occurrence of a duplicated record, use keep=False.

In [41]:
df.duplicated(keep=False)

0     True
1    False
2     True
dtype: bool

#### drop_duplicates()

The drop_duplicates() method removes duplicate rows from a DataFrame.

Syntax

df.drop_duplicates(subset=None, keep="first", inplace=False)

| Parameter       | Description                                             |
| --------------- | ------------------------------------------------------- |
| `subset`        | Columns to consider when identifying duplicates.        |
| `keep="first"`  | Retains the first occurrence.                           |
| `keep="last"`   | Retains the last occurrence.                            |
| `keep=False`    | Removes all occurrences of duplicated records.          |
| `inplace=False` | Returns a new DataFrame without modifying the original. |

In [42]:
df_cleaned = df.drop_duplicates()

print(df_cleaned)  #Important: The original index labels are preserved. drop_duplicates() does not automatically reset the index.

   Name  Age
0  Hari   25
1   Anu   28

#### Remove Duplicates from the Original DataFrame Variable

df = df.drop_duplicates()

#### Identify Duplicates Based on Specific Column

In [43]:
print(df.duplicated(subset=["Name"]))

#This checks only the Name column.

0    False
1    False
2     True
dtype: bool

#### Display Rows with Duplicate Names

In [ ]:
print(df[df.duplicated(subset=["Name"])])

#### Remove Duplicates Based on Specific Column

In [ ]:
df.drop_duplicates(
subset=['Name']
)

#### Keep Last Occurrence

In [ ]:

df.drop_duplicates(
subset=['Name'],
keep='last'