## Notebook 9 – Grouping & Aggregation

### 1. groupby()

The groupby() method is used to split data into groups based on one or more columns and then perform operations on each group.

It is similar to SQL's GROUP BY.

Syntax

df.groupby('column_name')

In [1]:
import pandas as pd

data = {
    "Name": ["Hari", "Kumar", "Ravi", "Priya", "Suresh", "Divya", "Arun"],
    "Department": ["IT", "HR", "IT", "HR", "IT", "Finance", "Finance"],
    "Salary": [25000, 35000, 30000, 28000, 45000, 40000, 32000],
    "Age": [22, 25, 23, 24, 28, 26, 23]
}

df = pd.DataFrame(data)

print(df)

     Name Department  Salary  Age
0    Hari         IT   25000   22
1   Kumar         HR   35000   25
2    Ravi         IT   30000   23
3   Priya         HR   28000   24
4  Suresh         IT   45000   28
5   Divya    Finance   40000   26
6    Arun    Finance   32000   23

In [2]:
df.groupby("Department")["Salary"].sum()

Department
Finance     72000
HR          63000
IT         100000
Name: Salary, dtype: int64

#Maximum Salary by Department

print(df.groupby("Department")["Salary"].max())

In [3]:
grouped = df.groupby("Department")

print(grouped)

<pandas.api.typing.DataFrameGroupBy object at 0x000001FAE5D7CA50>

#### Group by Multiple Columns

In [ ]:
df.groupby(
['Department', 'Location']
)['Salary'].sum()

#### Common Aggregations

df.groupby('Department')['Salary'].mean()

df.groupby('Department')['Salary'].max()

df.groupby('Department')['Salary'].min()

df.groupby('Department')['Salary'].count()

### 2. agg()

The agg() (aggregate) method is used to apply one or more aggregation functions to grouped data.

The main advantage of agg() is that you can perform multiple calculations on the same column or different columns using a single statement.

Syntax

df.groupby('column').agg(function)

#### Single Aggregation

In [ ]:
df.groupby('Department')['Salary'].agg('mean')

#### Multiple Aggregations

In [4]:
df.groupby('Department')['Salary'].agg(
['sum', 'mean', 'max', 'min']
)

               sum          mean    max    min
Department
Finance      72000  36000.000000  40000  32000
HR           63000  31500.000000  35000  28000
IT          100000  33333.333333  45000  25000

### 3. transform()

In Pandas, transform() is used to perform an operation on data and return a result that has the same number of rows as the original data.

It is especially useful when you want to calculate something for each group and add the result back to every row belonging to that group.

**Unlike agg(), it does not reduce rows.**

- Syntax

df.groupby("column_name")["numeric_column"].transform("function")

In [6]:
df = pd.DataFrame({
    'Department': ['IT', 'IT', 'HR', 'HR'],
    'Salary': [50000, 60000, 45000, 55000]
})

df['Dept_Avg'] = df.groupby('Department')['Salary'].transform('mean')

print(df)

  Department  Salary  Dept_Avg
0         IT   50000   55000.0
1         IT   60000   55000.0
2         HR   45000   50000.0
3         HR   55000   50000.0

- Imagine you have the following employee data:

| Name   | Department | Salary |
| ------ | ---------- | -----: |
| Hari   | IT         |  50000 |
| Kumar  | HR         |  40000 |
| Ravi   | IT         |  60000 |
| Priya  | HR         |  45000 |
| Suresh | Finance    |  55000 |
| Divya  | Finance    |  65000 |

Suppose you want to calculate the average salary of each department and display that average beside every employee in that department.

Your expected result would be:

| Name   | Department | Salary | Department_Avg_Salary |
| ------ | ---------- | -----: | --------------------: |
| Hari   | IT         |  50000 |                 55000 |
| Kumar  | HR         |  40000 |                 42500 |
| Ravi   | IT         |  60000 |                 55000 |
| Priya  | HR         |  45000 |                 42500 |
| Suresh | Finance    |  55000 |                 60000 |
| Divya  | Finance    |  65000 |                 60000 |

Notice something important:

Hari and Ravi belong to IT, so both receive the IT average salary of ₹55,000.
    
Kumar and Priya belong to HR, so both receive the HR average salary of ₹42,500.
    
Suresh and Divya belong to Finance, so both receive the Finance average salary of ₹60,000.

The average is calculated separately for each department, but the result is returned for every employee.

This is one of the main uses of transform().

### 4. filter()

n Pandas, filter() is used with groupby() to select or keep specific groups based on a condition. It returns the original rows belonging to the groups that satisfy the condition.

The filter() method removes entire groups based on a condition

Syntax

df.groupby('column').filter(function)

**Suppose you want to select only departments whose average salary is greater than ₹50,000.**

In [7]:
import pandas as pd

data = {
    "Name": ["Hari", "Kumar", "Ravi", "Priya", "Suresh", "Divya"],
    "Department": ["IT", "HR", "IT", "HR", "Finance", "Finance"],
    "Salary": [50000, 40000, 60000, 45000, 55000, 65000]
}

df = pd.DataFrame(data)

result = df.groupby("Department").filter(
    lambda group: group["Salary"].mean() > 50000
)

print(result)

     Name Department  Salary
0    Hari         IT   50000
2    Ravi         IT   60000
4  Suresh    Finance   55000
5   Divya    Finance   65000

In [8]:
df = pd.DataFrame({
    'Department': ['IT', 'IT', 'HR', 'Finance'],
    'Salary': [50000, 60000, 45000, 70000]
})

df.groupby('Department').filter(
    lambda x: len(x) > 1
)

  Department  Salary
0         IT   50000
1         IT   60000

### 5. Pivot Tables

In Pandas, pivot_table() is used to summarize and analyze data by grouping rows and columns and applying an aggregation function such as sum(), mean(), or count().

Suppose you want to calculate the total sales for each product in each region.

In [ ]:
import pandas as pd

data = {
    "Product": ["Laptop", "Mobile", "Laptop", "Mobile", "Laptop", "Mobile"],
    "Region": ["East", "East", "West", "West", "East", "West"],
    "Sales": [50000, 20000, 60000, 25000, 30000, 15000]
}

df = pd.DataFrame(data)

pivot = pd.pivot_table(
    df,
    values="Sales",
    index="Product",
    columns="Region",
    aggfunc="sum",
    fill_value=0
)

print(pivot)

### 6. Crosstab

A Crosstab (Cross Tabulation) calculates frequency counts between two or more categorical variables.

It is commonly used for categorical data analysis.

Syntax

pd.crosstab(row, column)

In [10]:
df = pd.DataFrame({
    'Department': ['IT', 'IT', 'HR', 'HR', 'IT'],
    'Gender': ['M', 'F', 'M', 'F', 'M']
})

pd.crosstab(
    df['Department'],
    df['Gender']
)

Gender      F  M
Department
HR          1  1
IT          1  2